#pragma checksum "C:\Users\tremc\Downloads\zodiacSign\Views\Shared\_Libra.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "5b14c8519c271a763d46a8ce3beebb4a045a07d8"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Shared__Libra), @"mvc.1.0.view", @"/Views/Shared/_Libra.cshtml")]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "C:\Users\tremc\Downloads\zodiacSign\Views\_ViewImports.cshtml"
using zodiacSign;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "C:\Users\tremc\Downloads\zodiacSign\Views\_ViewImports.cshtml"
using zodiacSign.Models;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"5b14c8519c271a763d46a8ce3beebb4a045a07d8", @"/Views/Shared/_Libra.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"bc2b4323c9b2996b550685be819a13dc2fb0f368", @"/Views/_ViewImports.cshtml")]
    #nullable restore
    public class Views_Shared__Libra : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    #nullable disable
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("class", new global::Microsoft.AspNetCore.Html.HtmlString("img-fluid"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("src", new global::Microsoft.AspNetCore.Html.HtmlString("~/images/Libra.PNG"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        #pragma warning restore 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral(@"<h1 class=""text-theme font-weight-bold"">Libra ZODIAC SIGN</h1>
<p class=""text-white underline"">
    Symbolized by <a href=""#"" class=""text-theme""> the scales</a> <span class=""ml-3"">Air Sign</span> 
    <span class=""ml-4"">Date <a href=""#"" class=""text-theme"">September 23rd - October 23rd</a></span>
    <span class=""ml-2"">Birthstone:</span> <span class=""ml-2 text-theme"">Peridot</span>
</p>
");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("img", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.SelfClosing, "5b14c8519c271a763d46a8ce3beebb4a045a07d84211", async() => {
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_0);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_1);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral(@"
<div class=""mt-2"">
    <h4 class=""text-white pt-3 mb-3"">Traits:</h4>
    <ul class=""d-flex flex-wrap"">
        <li class=""text-white border p-3"">Diplomatic</li>
        <li class=""text-white border p-3"">Fair</li>
        <li class=""text-white border p-3"">Social</li>
        <li class=""text-white border p-3"">Clever</li>
        <li class=""text-white border p-3"">Indecisive</li>
    </ul>
    <h4 class=""text-white pt-3 mb-3"">Libra in depth:</h4>
    <p class=""text-white"">
        Scales are the zodiac's only inanimate object and the symbol for Libra, an air sign, which emphasizes Libra's obsession with harmony and balance. Libra is preoccupied with symmetry and seeks to achieve harmony in all spheres of life. The zodiac's artists are represented by these air signs: Libras are passionate about fine art, intellectualism, and connoisseurship since Venus, the planet of love, beauty, and money, rules them. Suave Libras need to surround themselves with beautiful things and design spaces that are a reflect");
            WriteLiteral(@"ion of their fine preferences. These air indications are therefore fantastic stylists, art critics, designers, and decorators. While Libra's opposite sign, Aries, represents ""me,"" Libra symbolizes ""we"". Relationships are important to Libras because they find balance through friendship. They adore harmonious relationships with stylish companions, particularly those who make for desirable arm candy.
    </p>
</div>");
        }
        #pragma warning restore 1998
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; } = default!;
        #nullable disable
    }
}
#pragma warning restore 1591
