#pragma checksum "C:\Users\tremc\Downloads\zodiacSign\Views\Shared\_Pisces.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "732726b60484476a28228ddd8e16377d0546cf5e"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Shared__Pisces), @"mvc.1.0.view", @"/Views/Shared/_Pisces.cshtml")]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "C:\Users\tremc\Downloads\zodiacSign\Views\_ViewImports.cshtml"
using zodiacSign;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "C:\Users\tremc\Downloads\zodiacSign\Views\_ViewImports.cshtml"
using zodiacSign.Models;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"732726b60484476a28228ddd8e16377d0546cf5e", @"/Views/Shared/_Pisces.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"bc2b4323c9b2996b550685be819a13dc2fb0f368", @"/Views/_ViewImports.cshtml")]
    #nullable restore
    public class Views_Shared__Pisces : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    #nullable disable
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("class", new global::Microsoft.AspNetCore.Html.HtmlString("img-fluid"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("src", new global::Microsoft.AspNetCore.Html.HtmlString("~/images/Pisces.PNG"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        #pragma warning restore 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral(@"<h1 class=""text-theme font-weight-bold"">Pisce ZODIAC SIGN</h1>
<p class=""text-white underline"">
    Symbolized by <a href=""#"" class=""text-theme""> the Fishes</a> <span class=""ml-3"">Water Sign</span> 
    <span class=""ml-4"">Date <a href=""#"" class=""text-theme"">February 18th  - March 19th</a></span>
    <span class=""ml-2"">Birthstone:</span> <span class=""ml-2 text-theme"">Amethyst</span>
</p>
");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("img", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.SelfClosing, "732726b60484476a28228ddd8e16377d0546cf5e4218", async() => {
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_0);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_1);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral(@"
<div class=""mt-2"">
    <h4 class=""text-white pt-3 mb-3"">Traits</h4>
    <ul class=""d-flex flex-wrap"">
        <li class=""text-white border p-3"">Compassionate</li>
        <li class=""text-white border p-3"">Artistic</li>
        <li class=""text-white border p-3"">Emotional</li>
        <li class=""text-white border p-3"">Empathetic</li>
        <li class=""text-white border p-3"">Compassion</li>
    </ul>
    <h4 class=""text-white pt-3 mb-3"">Pisces in depth:</h4>
    <p class=""text-white"">
        The final sign of the zodiac is the water sign Pisces. Two fish swimming in opposite directions are used as a symbol to signify the continual divide of Pisces's focus between reality and dream. As the last sign, Pisces has absorbed all of the lessons that the other signs have learned, including the pleasures and sorrows, hopes and anxieties. This makes these fish the astrological wheel's most intuitive, sympathetic, and caring creatures. With such high emotional sensitivity, Pisces must be careful to keep thei");
            WriteLiteral(@"r feet firmly planted on the world of matter. Neptune, the heavenly body that rules imagination and dreams, rules Pisces, and this ethereal fish adores exploring its infinite imagination. Neptune, however, is also in charge of illusion and escape in its darker guise. Like the energy of the water, Neptunian energy is magical, enigmatic, and frequently terrifying. The horizon is obscured and the difference between the sea and the sky is impossible when the fog is thick on the ocean.
    </p>
</div>");
        }
        #pragma warning restore 1998
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; } = default!;
        #nullable disable
    }
}
#pragma warning restore 1591
