#pragma checksum "C:\Users\tremc\Downloads\zodiacSign\Views\Shared\_Taurus.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "c9180fd9f5c3b8f810df1f149eca8fb761d2db14"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Shared__Taurus), @"mvc.1.0.view", @"/Views/Shared/_Taurus.cshtml")]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "C:\Users\tremc\Downloads\zodiacSign\Views\_ViewImports.cshtml"
using zodiacSign;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "C:\Users\tremc\Downloads\zodiacSign\Views\_ViewImports.cshtml"
using zodiacSign.Models;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"c9180fd9f5c3b8f810df1f149eca8fb761d2db14", @"/Views/Shared/_Taurus.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"bc2b4323c9b2996b550685be819a13dc2fb0f368", @"/Views/_ViewImports.cshtml")]
    #nullable restore
    public class Views_Shared__Taurus : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    #nullable disable
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("class", new global::Microsoft.AspNetCore.Html.HtmlString("img-fluid"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("src", new global::Microsoft.AspNetCore.Html.HtmlString("~/images/Taurus.PNG"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        #pragma warning restore 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral(@"<h1 class=""text-theme font-weight-bold"">Taurus ZODIAC SIGN</h1>
<p class=""text-white underline"">Symbolized by <a href=""#"" class=""text-theme""> the Bull</a> <span class=""ml-3"">Earth Sign</span> <span class=""ml-4"">Date <a href=""#"" class=""text-theme""> April 20th - May 20th</a></span> <span class=""ml-2"">Birthstone:</span> <span class=""ml-2 text-theme"">Sapphire</span></p>
");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("img", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.SelfClosing, "c9180fd9f5c3b8f810df1f149eca8fb761d2db144193", async() => {
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_0);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_1);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral(@"
<div class=""mt-2"">
    <h4 class=""text-white pt-3 mb-3"">Traits:</h4>
    <ul class=""d-flex flex-wrap"">
        <li class=""text-white border p-3"">Aesthetics</li>
        <li class=""text-white border p-3"">Patience</li>
        <li class=""text-white border p-3"">Sensual</li>
        <li class=""text-white border p-3"">Nonchalant</li>
        <li class=""text-white border p-3"">Perseverance</li>
    </ul>
    <h4 class=""text-white pt-3 mb-3"">Taurus in depth:</h4>
    <p class=""text-white"">
        The bull is the symbol for Taurus, an earth sign. Taureans prefer unwinding in quiet, bucolic settings filled with soft sounds, calming fragrances, and sumptuous flavors, just like their celestial spirit animal. Venus, the alluring planet that rules romance, beauty, and wealth, rules Taurus. The earth sign of Taurus is the most sensuous in the zodiac due to the Venusian influence; these cosmic cows are seduced by any outward display of comfort and luxury. Taureans who are epicureans must have pleasure, and they ");
            WriteLiteral(@"are happiest when given attention. (Since Taurus rules the neck, these bulls are especially attracted to neck pats). It's true that Taureans would spend the entire day taking baths in a tub filled to the brim with aromatic oils. These earth signs are also aware of the worth of money. Taureans aren't hesitant to put in a lot of effort and work for significant benefits. They are driven, determined, and tough, and they feel safest when they consistently contribute to savings accounts.
    </p>
</div>");
        }
        #pragma warning restore 1998
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; } = default!;
        #nullable disable
    }
}
#pragma warning restore 1591
