#pragma checksum "C:\Users\tremc\Downloads\zodiacSign\Views\Shared\_Sagittarius.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "18eea5a33d436baba3c73ce5e911965ffdc5c1ee"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Shared__Sagittarius), @"mvc.1.0.view", @"/Views/Shared/_Sagittarius.cshtml")]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "C:\Users\tremc\Downloads\zodiacSign\Views\_ViewImports.cshtml"
using zodiacSign;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "C:\Users\tremc\Downloads\zodiacSign\Views\_ViewImports.cshtml"
using zodiacSign.Models;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"18eea5a33d436baba3c73ce5e911965ffdc5c1ee", @"/Views/Shared/_Sagittarius.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"bc2b4323c9b2996b550685be819a13dc2fb0f368", @"/Views/_ViewImports.cshtml")]
    #nullable restore
    public class Views_Shared__Sagittarius : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    #nullable disable
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("class", new global::Microsoft.AspNetCore.Html.HtmlString("img-fluid"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("src", new global::Microsoft.AspNetCore.Html.HtmlString("~/images/Sag.PNG"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        #pragma warning restore 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral(@"<h1 class=""text-theme font-weight-bold"">Sagittarius ZODIAC SIGN</h1>
<p class=""text-white underline"">
    Symbolized by <a href=""#"" class=""text-theme""> the Archer</a>
    <span class=""ml-3"">Fire Sign</span> <span class=""ml-4"">
        Date
        <a href=""#"" class=""text-theme""> November 22nd - December 20th</a>
    </span>
    <span class=""ml-2"">Birthstone:</span> <span class=""ml-2 text-theme"">Citrine</span>
</p>
");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("img", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.SelfClosing, "18eea5a33d436baba3c73ce5e911965ffdc5c1ee4271", async() => {
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_0);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_1);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral(@"
<div class=""mt-2"">
    <h4 class=""text-white pt-3 mb-3"">Traits:</h4>
    <ul class=""d-flex flex-wrap"">
        <li class=""text-white border p-3"">Optimistic</li>
        <li class=""text-white border p-3"">Lovers</li>
        <li class=""text-white border p-3"">Fair</li>
        <li class=""text-white border p-3"">Intellectual</li>
        <li class=""text-white border p-3"">Funny</li>
    </ul>
    <h4 class=""text-white pt-3 mb-3"">Sagittarius in depth:</h4>
    <p class=""text-white"">
        Being a changeable sign, Sagittarius is linked to flexibility and adaptability. This accurately captures the archers' ingrained drive for transformation. Sagittarians are born explorers, therefore it's crucial that they have the freedom to move about as they like. (Sagittarius regulates the thighs; as a result, these archers never stop moving.) These archers are known to travel the globe on thrill-seeking trips in pursuit of physical, intellectual, and spiritual explorations. Their restlessness fuels them. Because th");
            WriteLiteral(@"ey are constantly seeking out new information, Sagittarians excel as storytellers, entertainers, and artists. But it's not all fun and games: Sagittarius is known for being frank, and their ""brutal honesty"" frequently results in misunderstandings, poor communication, and a lot of bruised feelings. The good news, though?
    </p>
</div>");
        }
        #pragma warning restore 1998
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; } = default!;
        #nullable disable
    }
}
#pragma warning restore 1591
